### ISSUE TITLE
`/image/validate/tags` signature

### ISSUE THREAD

**Issue by davenquinn** [UW-Macrostrat/image-tagger-api#5]
I can't debug this until we get tags in the database, but I believe that the API signature for returning tags for validation is not what is needed by the UI. For each annotation/validation session, the UI asks for two things in sequence:

1. The image to tag (e.g. `/image/next` for tagging)
2. All currently set tags for that image (`/image/.../tags`)

It seems that the validation endpoint at `/image/validate/tags` returns a tag list for an image, which is the input anticipated for step 2. But this is backwards – I'd like to get the reference of an image with tags already set, and then request all tags for that image from the `/image/.../tags` route. Thus, instead of having the `/image/validate/tags` endpoint, we should have something like an `/image/validate` endpoint; that is, a functional equivalent of `/image/next` that picks a tagged, but not validated, image. This allows the UI code to be much simpler because it doesn't have to do anything different for a tagging and validating session.

(The above workflow does not account for multiple people tagging the same image completely separately, but that CAPTCHA-style interaction is not what we're going for here I suspect.)

**Comment by jczaplew** [comment]
Cool, makes sense. I will do the following:

1. Remove the `/image/validate/tags` endpoint 
2. Replace it with `/image/validate` which will return a random, not validated image 

@cambro said that eventually we should accommodate multiple validations. I'm thinking the following parameterizations:

1. `/image/validate` - get a random image for validation. May already be validated.
2. `/image/validate?validated=true` - get a random image for validation that has already been validated at least once
3. `/image/validate?validated=false` - get a random image for validation that has **not** been validated.

For this first pass we can use the third option.

**Comment by davenquinn** [comment]
Yep that sounds like a good solution.
